The Graph for NEAR Pathway
figment-networks/learn-web3-dapp pull request #202
Opened 2021-12-13 11:40 UTC by ALuhning

Ready for review.

If you need a graph api endpoint for testing (steps 7/8):  https://api.thegraph.com/subgraphs/name/aluhning/did-registry

2021-12-13 23:27 UTC, pyr0gan requested changes
Hi @ALuhning,

I've given this PR an initial review, and the structure is good however I think there are some points we'll have to work on a little bit. Please have a look over my comments, and just mark the conversations as resolved if you make a change and don't have any additional questions or concerns. If you leave a conversation unresolved, I'll get to it once you've made an initial round of fixes.

In particular, I'd like to hear what you think about possibly reusing _some_ of the API routes. I know you've gone with a Question and Answer approach, which isn't fully utilizing the structure of the pathways. It just bears a little more discussion is all. Overall, I have tested the pathway and it functions - I just think we may need to add some more detail in some places 😄

2021-12-13 23:27 UTC, pyr0gan commented on markdown/the_graph_near/SUBGRAPH_QUERY.md
> +If you have any feedback, reach out on [Discord](https://figment.io/devchat)!
We don't need to say this here, the following conclusion step covers the feedback (plus the Discord link is in the header!)

2021-12-13 23:27 UTC, pyr0gan commented on pages/api/the-graph-near/mapping.ts
> +const GRAPHQL_URL = process.env.NEXT_PUBLIC_LOCAL_SUBGRAPH as string;
Much like the other API routes, if we're not using this one (since the playground is on the Hosted Service) we can just remove the file.

2021-12-13 23:27 UTC, pyr0gan commented on markdown/the_graph_near/SUBGRAPH_SCAFFOLD.md
> +On Ethereum, a subgraph indexes events emitted by a smart contract, but on NEAR, we don't have events (at least not yet). The Graph for NEAR indexes blocks and receipts. The receipts may contain logs
I think it would be better to mention NEAR first, and Ethereum after (as a point of comparison).

2021-12-13 23:27 UTC, pyr0gan commented on markdown/the_graph_near/SUBGRAPH_QUERY.md
> +## 🥳 Enjoy the result of your work
I think we should rename this heading. It's a little out of flavour from the rest.

2021-12-13 23:27 UTC, pyr0gan commented on markdown/the_graph_near/SUBGRAPH_MAPPINGS.md
> +export function handleReceipt(receipt: near.ReceiptWithOutcome): void {
It appears the solution code already exists in https://github.com/VitalPointAI/near-subgraph-template/blob/master/src/mapping.ts so we'd want to remove the solution there or make a separate branch 😄

2021-12-13 23:27 UTC, pyr0gan commented on markdown/the_graph_near/SUBGRAPH_MAPPINGS.md
> +`Account` and `Log` are the imported objects (entities) we've just defined, and `receipt` is referencing the definition of a `receiptWithOutcome` made available in The Graph NEAR implementation. Spec
It may be beneficial to point out to the reader that the `ReceiptWithOutcome` and `ExecutionOutcome` are coming from `near-subgraph/node_modules/@graphprotocol/graph-ts/chain/near.ts. This will save a lot of confusion!

2021-12-13 23:27 UTC, pyr0gan commented on markdown/the_graph_near/SUBGRAPH_MANIFEST.md
> +2. **Remove all the comments**.
Is this actually necessary?

2021-12-13 23:27 UTC, pyr0gan commented on markdown/the_graph_near/SUBGRAPH_MANIFEST.md
> +If you open your NEAR-Subgraph-Template repository in a code editor like Visual Studio Code, you should see the manifest file called `subgraph.yaml`.
We should write with the assumption that users are on Gitpod, so they'll be in VSCode already.

2021-12-13 23:27 UTC, pyr0gan commented on markdown/the_graph_near/PROJECT_SETUP.md
> +## 🤔 What's The Graph for NEAR?
I think it would worthwhile to explain that users would want to complete the NEAR pathway and The Graph pathway to get the most benefit out of this pathway.

Overall, it's fine to have some repetition from The Graph pathway, but we want it to be unique, too!

2021-12-13 23:40 UTC, ALuhning commented on markdown/the_graph/FINAL.md
> +- 🔌 Overview of Graph nodes and The Graph Hosted Service
Oops, I accidentally changed the Ethereum final.md instead of the Graph/NEAR one.  Fixed.

2021-12-14 01:02 UTC, ALuhning commented on pages/api/the-graph-near/scaffold.ts
> +    fs.readFileSync('./subgraphs/punks/subgraph.yaml', 'utf8');
Alright - guess this is on me as I didn't fully grasp how the api routes were working.  I figured I needed a local Graph node running in order to make/check the code for these API calls.  So, I went looking for alternatives to check the work and figured a question/answer format was best.  However, just relooked at them and see that is not the case, so yeah, I'll switch things back and use the APIs.  I should have paid more attention, but instead decided to waste my time...doh.

api routes are now implemented.

2021-12-14 01:07 UTC, ALuhning commented on markdown/the_graph_near/SUBGRAPH_SCAFFOLD.md
> +Now it's time for you to verify that you have followed the instructions carefully.
changed back to api routes

2021-12-14 01:18 UTC, ALuhning commented on markdown/the_graph_near/SUBGRAPH_MANIFEST.md
> +If you open your NEAR-Subgraph-Template repository in a code editor like Visual Studio Code, you should see the manifest file called `subgraph.yaml`.
Note that that wording is also in the Ethereum/Graph pathway.  Regardless I've removed the reference to VSCode.

2021-12-14 03:49 UTC, ALuhning commented on markdown/the_graph_near/SUBGRAPH_QUERY.md
> +## 👨‍💻 Your turn! Write the GraphQL query
No issues doing this, but I note that none of the other files have the challenge heading either.  They aren't in the Ethereum/Graph pathway either.  They all start with Your turn!...

Acknowledged for the hints, will add where appropriate.  Let me know which one you want me to go with.

2021-12-14 03:51 UTC, ALuhning commented on markdown/the_graph_near/SUBGRAPH_QUERY.md
> +If you have any feedback, reach out on [Discord](https://figment.io/devchat)!
Ok, I've removed, but again - the Ethereum/Graph pathway has this at the bottom of the same file.

2021-12-14 13:03 UTC, zurgl commented
@pyr0gan Please do not merge the PR. I need to do a quick technical review of it.
@ALuhning I'll wait that @pyr0gan has finished and approved his review to start mine.

2021-12-14 17:09 UTC, ALuhning commented on markdown/the_graph_near/SUBGRAPH_SCHEMA.md
> +The DID Registry contract is outputting logs in the following format for the `init` and `putDID` methods.
Added some explanation to the project setup to set the stage.

2021-12-14 17:14 UTC, ALuhning commented on markdown/the_graph_near/SUBGRAPH_SCAFFOLD.md
> +> Note: You need to be using node >= 14.17
Noted that it's in the readme under clone locally section, so yep, removing it.

2021-12-15 17:28 UTC, pyr0gan approved these changes
@ALuhning Thanks for the quick edits! Just a couple of small tweaks and we can move to internal testing.

@zurgl I think it's good, you can review when you have time! 😄

2021-12-15 17:28 UTC, pyr0gan commented on components/protocols/the_graph_near/lib/index.tsx
> +export const toEther = (amountInWei: WEI): ETH => {
Not required for this pathway, we can remove the Ethereum functions from this file 👍

2021-12-15 17:28 UTC, pyr0gan commented on components/protocols/the_graph_near/lib/index.tsx
> +export const getEtherScanContract = (address: string) => {
Could be repurposed to display a NEAR account on the NEAR explorer, for this pathway?

2021-12-15 17:28 UTC, pyr0gan commented on markdown/the_graph/FINAL.md
> +🥳 **Congratulations**, you have completed the Graph for NEAR Pathway! \
This change is incorrect and can be reverted (You likely meant to edit `markdown/the_graph_near/FINAL.md`)

2021-12-15 17:28 UTC, pyr0gan commented on markdown/the_graph_near/FINAL.md
> +🥳 **Congratulations**, you have completed the Graph Pathway! \
I think you meant to edit this file to mention NEAR but ended up doing it in `the_graph/FINAL.md` by accident.

2021-12-15 17:28 UTC, pyr0gan commented on markdown/the_graph_near/SUBGRAPH_SCAFFOLD.md
> +Once the template has been cloned, change into the near-subgraph directory and install the dependencies with npm. Assuming you're using Gitpod, you can use the terminal command code <filename> to ope
> ... use the terminal command `code <filename>` to open a file, or navigate to the file in the Explorer panel and click on the filename.

note: preformatted text for terminal commands helps them to stand out for readers 😄

2021-12-15 17:28 UTC, pyr0gan commented on markdown/the_graph_near/SUBGRAPH_SCAFFOLD.md
> +You will need to look in subgraph.yaml, schema.graphql and src/mapping.ts
> You will need to look in `subgraph.yaml`, `schema.graphql` and `src/mapping.ts`.

note: preformatted text for filenames, too 😁

2021-12-15 17:28 UTC, pyr0gan commented on markdown/the_graph_near/SUBGRAPH_QUERY.md
> +## 👨‍💻 Your turn! Write the GraphQL query
> No issues doing this, but I note that none of the other files have the challenge heading either. They aren't in the Ethereum/Graph pathway either. They all start with Your turn!...

You're right, they do. It isn't a _hard_ requirement, just trying to stay consistent but I'd forgotten we changed it up a little for that pathway.  We can leave headings as is, I think the hints are the important part.

2021-12-15 17:28 UTC, pyr0gan commented on markdown/the_graph_near/GRAPH_NODE.md
> +Getting started with [the hosted service](https://thegraph.com/hosted-service/) is simply a matter of signing up using your Github login credentials. Once inside, navigate to your dashboard. This is
> Getting started with [the Hosted Service](https://thegraph.com/hosted-service/) is simply a matter of signing up using your Github login credentials. ...

I think it's "Hosted Service" everywhere else, just noticed this link text was in lowercase.

2021-12-15 17:28 UTC, pyr0gan commented on markdown/the_graph_near/GRAPH_NODE.md
> +## 👨‍💻 Setting up the Graph hosted service
> \## 👨‍💻 Using the Hosted Service

2021-12-15 18:46 UTC, ALuhning commented on components/protocols/the_graph_near/lib/index.tsx
> +export const getEtherScanContract = (address: string) => {
I repurposed it, but I can't see where the original getEtherScanContract function is being called anywhere, so not sure where we'd want to link to the near contract by calling this function?

2021-12-15 18:55 UTC, ALuhning commented
@pyr0gan - do you figure I'm safe to go ahead and shoot the walkthrough video now?  Would you prefer one video from start to finish or would it be ok if I made several shorter ones - one for each step?

2021-12-15 19:09 UTC, pyr0gan commented
> @pyr0gan - do you figure I'm safe to go ahead and shoot the walkthrough video now? Would you prefer one video from start to finish or would it be ok if I made several shorter ones - one for each step?

I recommend we get a few community members to beta test it, to see if there is any useful feedback to incorporate. I am going to organize their run through it and collect the feedback, which I will then summarize for you so we can make a final polish pass. Then it would be ideal to make the video content! Saves you from having to re-do anything 😄 I believe we are most of the way there, but we want to ensure quality so getting fresh eyes on it is important.

2021-12-16 20:37 UTC, pyr0gan commented
@ALuhning I've got a few testers currently working through the pathway, I expect they will provide their feedback soon and I'll be able to summarize it for you - likely in a Discord conversation 😄

2021-12-16 23:21 UTC, pyr0gan requested changes
Some feedback and sugested changes based on user testing.

2021-12-16 23:21 UTC, pyr0gan commented on markdown/the_graph_near/SUBGRAPH_MAPPINGS.md
> +Now it's time for you to verify that you have followed the instructions carefully. Click on the **Check subgraph deployment** button on the right to check that your subgraph has been deployed to the
> Now it's time for you to verify that you have followed the instructions carefully. Copy and paste the endpoint URL from your dashboard (the one under Queries (HTTP)!) then click on the **Check subgraph deployment** button on the right to check that your subgraph has been deployed to the Hosted Service.

2021-12-16 23:21 UTC, pyr0gan commented on markdown/the_graph_near/SUBGRAPH_SCAFFOLD.md
> +Once the template has been cloned, change into the near-subgraph directory and install the dependencies with npm. Assuming you're using Gitpod, you can use the terminal command `code <filename>` to o
> Once the template has been cloned, change into the `near-subgraph` directory and install the dependencies with npm. 
> Assuming you're using Gitpod, you can use the terminal command `code <filename>` to open a file, or navigate to the file in the Explorer panel and click on the filename. You can review the scaffolded files by looking in `subgraph.yaml`, `schema.graphql` and `src/mapping.ts`.

2021-12-16 23:21 UTC, pyr0gan commented on markdown/the_graph_near/GRAPH_NODE.md
> +![hosted](https://raw.githubusercontent.com/figment-networks/learn-web3-dapp/main/markdown/__images__/the-graph-near/hosted-01.png)
These image links will work once we've merged the PR, but it would still be good to add `?raw=true` to the end of each image URL just to make sure they display properly in all cases. I've seen images fail to load even when using the raw.githubusercontent.com domain, but using `?raw=true` will ensure they load everywhere.

2021-12-16 23:59 UTC, ALuhning commented on markdown/the_graph_near/SUBGRAPH_MAPPINGS.md
> +First, open `src/mapping.ts`.
It'll be partially complete - first function mapping ("putDID") will be done and then they'll just fill in the function mapping for the "init" function.

2021-12-17 00:09 UTC, ALuhning commented on markdown/the_graph_near/SUBGRAPH_MAPPINGS.md
> +At last, we call `logs.save()` and then push the log onto the account entity with `accounts.log.push(logs.id)`.
It's `accounts` - probably confused becuase I had the wrong code in the lesson earlier which is not fixed/synched to the repo.

2021-12-17 00:15 UTC, ALuhning commented on markdown/the_graph_near/SUBGRAPH_MAPPINGS.md
> +Your `src/mapping.ts` should look like this:
I think we go with the second otherwise you get a very long block of code.  Have changed it to the "Make sure that you ..." one.

2021-12-17 00:17 UTC, ALuhning commented on markdown/the_graph_near/SUBGRAPH_MAPPINGS.md
> +}
Yes, it's already in the template - ref the comment // Your turn! Write underneath that code, but before accounts.save();

2021-12-21 11:38 UTC, zurgl requested changes

2021-12-21 11:38 UTC, zurgl commented on pages/the_graph_near.tsx
> +
@ALuhning We have done some modifications on our side and they have been merged to main. You will need to adapt your code otherwise.

Could you please import NoSSR component and wrap the Layout with it?
Thanks

Reference:
https://github.com/figment-networks/learn-web3-dapp/blob/main/pages/avalanche.tsx#L5

2021-12-22 06:33 UTC, pyr0gan reviewed
There's a small issue to fix with the `npm install` command as mentioned in the comment contained in this review.

2021-12-23 17:55 UTC, pyr0gan approved these changes

2021-12-23 20:11 UTC, zurgl approved these changes

2021-12-23 23:54 UTC, pyr0gan commented
My only concern at this point is the look of the button on the initial protocols page:
<img width="350" alt="Screen Shot 2021-12-23 at 1 19 54 PM" src="https://user-images.githubusercontent.com/2707197/147288297-a26bb5fb-eb51-4f79-98e8-ef3293838267.png">

We need to downsize the icon a little, and maybe even tweak the font size so that it has a consistent look with the rest of the buttons. I played around with it a little but I could not arrive at a satisfactory look with the text flowing across two lines. Even just "GRT + NEAR" did not fit on one line at the fint size we are using.

2021-12-24 01:15 UTC, ALuhning commented
I actually figured you guys had standard images/buttons you would use for that - I just threw that in as a placeholder.  Not much of a graphic design artist, but if you want me to try and do something with it I will.

2021-12-24 02:11 UTC, pyr0gan commented
> I actually figured you guys had standard images/buttons you would use for that - I just threw that in as a placeholder. Not much of a graphic design artist, but if you want me to try and do something with it I will.

There isn't any graphic design required, we can use the existing NEAR icon - this is just about tweaking the styling 😄 
I'll handle the necessary edits @ALuhning.

2021-12-29 16:34 UTC, pyr0gan commented
@ALuhning It will be simpler to make sure the title defined in `constants.ts` fits on one line - I think "NEAR Graph" will suffice. We designed the protocol boxes to be pretty tight and I don't think increasing their size for the sake of wrapping text gracefully is the play. I'll make the edit post-merge! Thanks again for all the work you put into this, we appreciate it 😄

2021-12-29 16:35 UTC, merged