Update Secret.JS to 1.6.5
figment-networks/learn-web3-dapp pull request #292
Opened 2022-12-31 08:44 UTC by levackt

Updated code and docs of Secret.JS to the latest version

2023-01-12 19:56 UTC, pyr0gan requested changes
Overall, this looks good and thank you for the help in updating this pathway.

Just a few suggestions for improvement before we merge this PR 👍

2023-01-12 19:56 UTC, pyr0gan commented on markdown/secret/DEPLOY_CONTRACT.md
>    - Optionally, we could also include a memo, a transfer amount, fees, and a code hash. For this example, these arguments are unnecessary.
There needs to a be a little more explanation here since the contract address needs to be fulfilled for the page to work.

I recommend the following:

> **What happened in the code above?**

> - First, we upload the contract using `storeCode` method of the `SecretNetworkClient`.
> - Next, we searched the arrayLog in the `uploadReceipt` response object to find the `code_id` of the deployed contract
> - Finally, we instantiate the contract using `instantiateContract` method of the `SecretNetworkClient`, passing:
>  - The `code_id`.
>  - The `init_msg` contract method to instantiate the storage with a value of `101`.
>  - A label, which needs to be unique, which is why we use a random number.
>  - We set the transaction gas limit to the constant value `INIT_GAS_LIMIT`.
>  - Optionally, we could also include a memo, a transfer amount, fees, and a code hash. For this example, these arguments are unnecessary.
> - To find the deployed address of the contract, we can look in the receipt logs using the `find` method from JavaScript. As noted in the code comment, you could also parse the JSON response.

2023-01-12 19:56 UTC, pyr0gan commented on markdown/secret/DEPLOY_CONTRACT.md
> +const uploadReceipt = await client.tx.compute.undefined;
We should update the challenge here to mention the contract address while we're at it. Go with this:

```js
    // Upload the contract wasm
    const wasm = fs.readFileSync(CONTRACT_PATH);

    const uploadReceipt = await client.tx.compute.undefined;
   
    // Get the code ID from the receipt
    const {codeId} = uploadReceipt;

    // Create an instance of the Counter contract, providing a starting count
    const initMsg = {count: 101};
    const receipt = await client.undefined;

    const contractAddress = undefined;
```

2023-01-12 19:56 UTC, pyr0gan commented on markdown/secret/DEPLOY_CONTRACT.md
> +const uploadReceipt = await client.tx.compute.storeCode(
The solution should look like this (without the contract address, the step would fail). This matches the example in the SecretJS repo.

```js
    // Upload the contract wasm
    const wasm = fs.readFileSync(CONTRACT_PATH);
    const uploadReceipt = await client.tx.compute.storeCode(
      {
        sender: wallet.address,
        wasm_byte_code: wasm,
        source: '',
        builder: '',
      },
      {
        gasLimit: STORE_CODE_GAS_LIMIT,
      },
    );

    // Get the code ID from the receipt
    const codeId = Number(
      uploadReceipt.arrayLog.find(
        (log: {type: string; key: string}) =>
          log.type === 'message' && log.key === 'code_id',
      ).value,
    );

    // Contract hash, useful for contract composition
    const contractCodeHash = (
      await client.query.compute.codeHashByCodeId({code_id: codeId})
    ).code_hash;
    console.log(`Contract hash: ${contractCodeHash}`);

    // Create an instance of the Counter contract, providing a starting count
    const initMsg = {count: 101};
    const receipt = await client.tx.compute.instantiateContract(
      {
        code_id: codeId,
        sender: wallet.address,
        code_hash: contractCodeHash, // this is optional but makes contract executions much faster
        init_msg: initMsg,
        label: 'Simple Counter' + Math.ceil(Math.random() * 100000),
      },
      {
        gasLimit: INIT_GAS_LIMIT,
      },
    );

    // Get the contract_address from the logs
    const contractAddress = receipt.arrayLog.find(
      (log: {type: string; key: string}) =>
        log.type === 'message' && log.key === 'contract_address',
    ).value;

    // An alternate way to reach the contract address
    // const contractAddress = JSON.parse(receipt?.rawLog)[0].events[0]
    // .attributes[3].value;
```

2023-01-12 19:56 UTC, pyr0gan commented on markdown/secret/GET_BALANCE.md
> +    res.status(200).json(balance?.amount || '0')
👍

2023-01-12 19:56 UTC, pyr0gan commented on markdown/secret/GET_BALANCE.md
> +- We check the balance by querying the bank module and accessing the `amount` property of the `balance object returned`. The `balance` here is an optional <Coin> in the QueryBalanceResponse TypeScrip
> We check the balance by querying the bank module and accessing the `amount` property of the `balance object returned`. The `balance` here is an optional <Coin> in the QueryBalanceResponse TypeScript definition.

Should be 

> We check the balance by querying the bank module and accessing the `amount` property of the `balance` object returned. The `balance` here is an optional <Coin> in the QueryBalanceResponse TypeScript definition.

2023-01-12 19:58 UTC, pyr0gan commented
I should also point out that you'll want to pull from the origin's main branch before we can merge this PR as there were some changes (removal of links to the discontinued community Discord server) 😄

2023-01-15 06:16 UTC, levackt commented on markdown/secret/DEPLOY_CONTRACT.md
> +const uploadReceipt = await client.tx.compute.storeCode(
Great, thanks, I left out the code hash for simplicity but it's well worth mentioning

2023-01-15 06:22 UTC, levackt commented
Thanks for the perusal, let me know if you need anything else

2023-01-16 18:27 UTC, pyr0gan approved these changes

2023-01-16 19:03 UTC, merged